feat: add notifications service
app-anvil/a2f_sdk pull request #6
Opened 2024-05-05 10:39 UTC by mrcsilverfox

Closes #5

2024-05-06 15:09 UTC, gianmarcocalbi requested changes

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/core/stream/stream_controller_handler.dart
> +    _streamController.add(null);
perché aggiungere `null` è un reset?

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
> +class NotificationsService with LoggerMixin {
```suggestion
class NotificationService with LoggerMixin {
```

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
rinomina il file al singolare

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
> +/// {@template notifications_service}
```suggestion
/// {@template notification_service}
```

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
> +/// plugina, show (local and push) and schedule (local) notifications.
```suggestion
/// This service is in charge of configuring the flutter_local_notifications
/// plugin, showing (local and push) and scheduling (local) notifications.
```

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
in questo file vedo tante cose specifiche sia per le piattaforme che per Waste Not in particolare, in tal caso non è da inserire nell'SDK

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/notifications_service.dart
> +    required DateTime when,
```suggestion
    required DateTime schedule,
```

`when` è una keyword riservata in Dart

2024-05-06 15:09 UTC, gianmarcocalbi commented on lib/src/notifications/received_notification.dart
> +      body: body ?? 'Clicca su questa notifica per vedere i dettagli',
troppo specifico per stare nell'SDK

2024-05-06 15:39 UTC, mrcsilverfox commented on lib/src/core/stream/stream_controller_handler.dart
> +    _streamController.add(null);
lo stream non viene resettato, se si può fare lo resetto. Viene solo aggiunto un altro elemento per impedire che venga manipolato due volte l'oggetto.

2024-05-06 15:41 UTC, mrcsilverfox commented on lib/src/notifications/notifications_service.dart
che palle quindi per ogni app bisogna copiarsi sta roba qui??

2024-05-06 15:41 UTC, mrcsilverfox commented on lib/src/notifications/received_notification.dart
> +      body: body ?? 'Clicca su questa notifica per vedere i dettagli',
No perché? Possiamo togliere il valore di default, sono sempre gestite cosi le notifiche.

2024-07-01 18:37 UTC, gianmarcocalbi commented
La chiudo. Al massimo la riapriamo più avanti

2024-07-01 18:37 UTC, closed without merging